In [48]:
# 输入部分
plist=[0.52765777,0.27438587,0.19795635]
peilv=[1.21,4.60,10.50]
M=1000#总规划资金
FF=-200#最低愿意承担的风险值或期望获利值

In [49]:
def fun(x):
    Exp=-(x[0]*plist[0]*peilv[0]+x[1]*plist[1]*peilv[1]+x[2]*plist[2]*peilv[2]-M)
    return Exp
fun1=lambda x:M-(x[0]+x[1]+x[2])
fun2=lambda x:x[0]*peilv[0]-(M)-FF
fun3=lambda x:x[1]*peilv[1]-(M)-FF
fun4=lambda x:x[2]*peilv[2]-(M)-FF
_constraints=({'type':'ineq','fun':fun1},{'type':'ineq','fun':fun2} ,{'type':'ineq','fun':fun3},{'type':'ineq','fun':fun4})  # 限制，ineq代表不等于,eq代表等于
_bounds=((0,M),(0,M),(0,M))  # 优化范围
import scipy.optimize as so
result=so.minimize(fun,(M/3,M/3,M/3),method='SLSQP',
                   bounds=_bounds,constraints=_constraints)
print(result)
if result.success==False:
    print("这场达不到期望，投注不了")
else:
    print("期望值：",-result.fun)
    print("W投注",result.x[0])
    print("P投注",result.x[1])
    print("F投注",result.x[2])
    x=result.x
    print("最终结果为胜利的获利：",x[0]*peilv[0]-M)
    print("最终结果为平局的获利：",x[1]*peilv[1]-M)
    print("最终结果为负局的获利：",x[2]*peilv[2]-M)

     fun: 15.55135144964288
     jac: array([-0.63846588, -1.26216888, -2.07853699])
 message: 'Optimization terminated successfully'
    nfev: 12
     nit: 3
    njev: 3
  status: 0
 success: True
       x: array([661.15702479, 173.91304348, 164.92993173])
期望值： -15.55135144964288
W投注 661.1570247947648
P投注 173.91304347819073
F投注 164.92993172704456
最终结果为胜利的获利： -199.9999999983346
最终结果为平局的获利： -200.00000000032276
最终结果为负局的获利： 731.7642831339679


In [34]:
def fun(x):
    Exp=-(x[0]*plist[0]*peilv[0]+x[1]*plist[1]*peilv[1]+x[2]*plist[2]*peilv[2])
    return Exp
fun1=lambda x:M-(x[0]+x[1]+x[2])
fun2=lambda x:x[0]*peilv[0]-(M-x[0])-FF
fun3=lambda x:x[1]*peilv[1]-(M-x[1])-FF
fun4=lambda x:x[2]*peilv[2]-(M-x[2])-FF
_constraints=({'type':'ineq','fun':fun1},{'type':'ineq','fun':fun2} ,{'type':'ineq','fun':fun3},{'type':'ineq','fun':fun4})  # 限制，ineq代表不等于,eq代表等于
_bounds=((0,M),(0,M),(0,M))  # 优化范围
import scipy.optimize as so
result=so.minimize(fun,(M/3,M/3,M/3),method='COBYLA',
                   bounds=_bounds,constraints=_constraints)
print(result)
if result.success==False:
    print("这场达不到期望，投注不了")
else:
    print("期望值：",-result.fun)
    print("W投注",result.x[0])
    print("P投注",result.x[1])
    print("F投注",result.x[2])
    x=result.x
    print("最终结果为胜利的获利：",x[0]*peilv[0]-(M-x[0]))
    print("最终结果为平局的获利：",x[1]*peilv[1]-(M-x[1]))
    print("最终结果为负局的获利：",x[2]*peilv[2]-(M-x[2]))

     fun: -1281.1439149959601
   maxcv: -0.0
 message: 'Optimization terminated successfully.'
    nfev: 328
  status: 1
 success: True
       x: array([452.48868778, 178.57142857, 368.93988365])
期望值： 1281.1439149959601
W投注 452.4886877828054
P投注 178.5714285714286
F投注 368.939883645766
最终结果为胜利的获利： 0.0
最终结果为平局的获利： 2.2737367544323206e-13
最终结果为负局的获利： 3242.8086619263086


In [35]:
def fun(x):
    Exp=-(x[0]*plist[0]*peilv[0]+x[1]*plist[1]*peilv[1]+x[2]*plist[2]*peilv[2]-M)
    return Exp
fun1=lambda x:M-(x[0]+x[1]+x[2])
fun2=lambda x:x[0]*peilv[0]-(M-x[0])-FF
fun3=lambda x:x[1]*peilv[1]-(M-x[1])-FF
fun4=lambda x:x[2]*peilv[2]-(M-x[2])-FF
_constraints=({'type':'ineq','fun':fun1},{'type':'ineq','fun':fun2} ,{'type':'ineq','fun':fun3},{'type':'ineq','fun':fun4})  # 限制，ineq代表不等于,eq代表等于
_bounds=((0,M),(0,M),(0,M))  # 优化范围
import scipy.optimize as so
result=so.minimize(fun,(M/3,M/3,M/3),method='SLSQP',
                   bounds=_bounds,constraints=_constraints)
print(result)
if result.success==False:
    print("这场达不到期望，投注不了")
else:
    print("期望值：",-result.fun)
    print("W投注",result.x[0])
    print("P投注",result.x[1])
    print("F投注",result.x[2])
    x=result.x
    print("最终结果为胜利的获利：",x[0]*peilv[0]-(M-x[0]))
    print("最终结果为平局的获利：",x[1]*peilv[1]-(M-x[1]))
    print("最终结果为负局的获利：",x[2]*peilv[2]-(M-x[2]))

     fun: -281.1439149959581
     jac: array([-0.63847351, -1.26217651, -2.07853699])
 message: 'Optimization terminated successfully'
    nfev: 32
     nit: 9
    njev: 8
  status: 0
 success: True
       x: array([452.48868778, 178.57142857, 368.93988365])
期望值： 281.1439149959581
W投注 452.48868778280547
P投注 178.57142857143089
F投注 368.9398836457637
最终结果为胜利的获利： 1.1368683772161603e-13
最终结果为平局的获利： 1.2960299500264227e-11
最终结果为负局的获利： 3242.808661926282


# 简单回归模型
考虑参数为排名与身价

In [3]:
a1,b1,c1,d1=18,8,2.53,3.39

In [4]:
import matplotlib.pyplot as plt
import numpy as np
import warnings
import matplotlib.pyplot as plt
from sklearn import metrics
warnings.filterwarnings("ignore")
train=np.loadtxt("X-data.csv",str,delimiter = ",",skiprows = 1)
y=train[:,-1]
ytrain=np.array([int(i) for i in y])
Xtrain=train[:,:-1]
xtrain=Xtrain.astype(float)
X=xtrain
print(X)
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error
import warnings
warnings.filterwarnings("ignore")
model1=LogisticRegression(multi_class='multinomial',solver="lbfgs",max_iter=1000)
model1.fit(X,y)
model1.score(X,y)

[[ 1.     30.      4.43    0.3365]
 [ 1.     61.      5.86    0.74  ]
 [ 1.     24.      5.22    0.4785]
 ...
 [ 1.     28.      3.64    1.11  ]
 [31.     28.      0.0732  1.2   ]
 [20.     28.      0.3888  1.16  ]]


0.5735294117647058

In [5]:
test=np.array([a1,b1,c1,d1])
test=test.reshape(-1,4)
print(test)
ype_m1=model1.predict_proba(test)
ype1=model1.predict(test)
print("胜负预测：",ype1)
print("P:",ype_m1)

[[18.    8.    2.53  3.39]]
胜负预测： ['-1']
P: [[0.45163944 0.28207891 0.26628165]]


In [53]:
from sklearn import tree #导入需要的模块
clf = tree.DecisionTreeClassifier(max_depth=3,min_samples_leaf=3,min_samples_split=3)
clf.fit(X,y)
yscore=clf.score(X,y)
print(yscore)


0.5772058823529411


In [54]:
test=np.array([a1,b1,c1,d1])
test=test.reshape(-1,4)
ype_m2=clf.predict_proba(test)
ype1=clf.predict(test)
print("胜负预测：",ype1)
print("P:",ype_m2)

胜负预测： ['-1']
P: [[0.47826087 0.22529644 0.29644269]]


In [55]:
from sklearn.datasets import load_iris
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=3)
model.fit(X, y)
yscore=model.score(X,y)
print(yscore)

0.8970588235294118


In [56]:
test=np.array([a1,b1,c1,d1])
test=test.reshape(-1,4)
ype=model.predict_proba(test)
ype1=model.predict(test)
print("胜负预测：",ype1)
print("P:",ype)

胜负预测： ['1']
P: [[0. 0. 1.]]


In [57]:
from sklearn.svm import SVC
svc=SVC(C=1000,kernel='rbf',gamma='scale',probability=True,decision_function_shape='ovo',random_state=30)
svc.fit(X,y)
score=svc.score(X,y)
print("正确率",score)

正确率 0.5919117647058824


In [58]:
test=np.array([a1,b1,c1,d1])
test=test.reshape(-1,4)
ype_3=svc.predict_proba(test)
ype1=svc.predict(test)
print("胜负预测：",ype1)
print("P:",ype_3)

胜负预测： ['-1']
P: [[0.50017326 0.24251034 0.2573164 ]]


In [59]:
from sklearn.ensemble import VotingClassifier
log_clf=LogisticRegression(multi_class='multinomial',solver="lbfgs",random_state=26)
rnd_clf=RandomForestClassifier(n_estimators=30,random_state=42)
svc_clf=svc=SVC(gamma='scale',random_state=25)
vclf=VotingClassifier(estimators=[('lr',log_clf),('rf',rnd_clf),('svc',svc_clf)],voting='hard')
vclf.fit(X,y)
score=vclf.score(X,y)
print("正确率",score)
test=np.array([a1,b1,c1,d1])
test=test.reshape(-1,4)
#ype=vclf.predict_proba(test)
ype1=vclf.predict(test)
print("胜负预测：",ype1)


正确率 0.5882352941176471
胜负预测： ['-1']


In [60]:
from sklearn.naive_bayes import GaussianNB
bayes = GaussianNB()
bayes=bayes.fit(X, y)
score=bayes.score(X,y)
ypre=bayes.predict(X)
print("正确率",score)

正确率 0.6102941176470589


In [61]:
test=np.array([a1,b1,c1,d1])
test=test.reshape(-1,4)
ype_4=bayes.predict_proba(test)
ype1=bayes.predict(test)
print("胜负预测：",ype1)
print("P:",ype_4)

胜负预测： ['-1']
P: [[0.44407877 0.28448641 0.27143482]]


使用神经网络的结果不佳

In [64]:
av=(ype_m1+ype_m2+ype_3+ype_4)/4
print(av)

[[0.46853809 0.25859302 0.27286889]]


In [63]:
av=(ype_m1+ype_m2+ype_3)/3
print(av)

[[0.47669119 0.2499619  0.27334691]]


# 最新尝试
使用凯利公式

定义总预期投资N

$<\Delta lnN>=\sum_{i=1}^n p_iln(1+r_if)$



In [65]:

# 输入部分
plist=[0.49286595,0.24832211,0.25881194]
peilv=[1.21,4.60,10.50]
M=1000#总规划资金
# FF=-300#最低愿意承担的风险值或期望获利值
rlist=[i-1 for i in peilv]
print(rlist)
explist=[rlist[i]*plist[i]-(1-plist[i]) for i in range(0,3)]
print(explist)
g=[]
def Kaili(i):
    sum=0
    sum=(peilv[i]*plist[i]-1)/(peilv[i]-1)
    return sum
for i in range(0,3):
    if explist[i]>0:
        if i==0:
            temp = '胜'
        if i==1:
            temp = '平'
        if i==2:
            temp = '负'
        print("下注压 {} 期望大于0，可以进行后续规划".format(temp))
        K=Kaili(i)
        print("由凯利公式得出投资比例为：{}".format(K))
        g.append(K)
    else:
        g.append(0)
if sum(g)==0:
    print("本场期望小于0，不值得押注")

[5, 2.65, 0.42999999999999994]
[0.63721334, -0.0561354770000001, -0.3299905313]
下注压 胜 期望大于0，可以进行后续规划
由凯利公式得出投资比例为：0.12744266799999995


In [66]:
def fun(x):
    Exp=-(x[0]*plist[0]*peilv[0]+x[1]*plist[1]*peilv[1]+x[2]*plist[2]*peilv[2])
    return Exp
fun1=lambda x:M-(x[0]+x[1]+x[2])
fun2=lambda x:M*g[0]-x[0]
fun3=lambda x:M*g[1]-x[1]
fun4=lambda x:M*g[2]-x[2]
_constraints=({'type':'ineq','fun':fun1},{'type':'ineq','fun':fun2} ,{'type':'ineq','fun':fun3},{'type':'ineq','fun':fun4})  # 限制，ineq代表不等于,eq代表等于
_bounds=((0,M),(0,M),(0,M))  # 优化范围
import scipy.optimize as so
result=so.minimize(fun,(M/3,M/3,M/3),method='COBYLA',
                   bounds=_bounds,constraints=_constraints)
if result.success==False:
    print("这场达不到期望，投注不了")
else:
    print("W投注",result.x[0])
    print("P投注",result.x[1])
    print("F投注",result.x[2])
    x=result.x
    c=x[0]+x[1]+x[2]
    print("投入资金总数：",c)
    print("最终结果为胜利的获利：",x[0]*peilv[0]-(c-x[0]),'预测概率为',plist[0])
    print("最终结果为平局的获利：",x[1]*peilv[1]-(c-x[1]),'预测概率为',plist[1])
    print("最终结果为负局的获利：",x[2]*peilv[2]-(c-x[2]),'预测概率为',plist[2])
    print("与只投注一种结果相比")
    print("只压胜投入：",M*g[0])
    print("最终结果为胜利的获利：",x[0]*peilv[0]-M*g[0],'预测概率为',plist[0])
    print("损失：",M*g[0],'的概率',1-plist[0])
    if g[0]!=0:
        print("风险回报比",M*g[0]*peilv[0]/M/g[0])
    print("只压平投入：",M*g[1])
    print("最终结果为平局的获利：",x[1]*peilv[1]-M*g[1],'预测概率为',plist[1])
    print("损失：",M*g[1],'的概率',1-plist[1])
    if g[1]!=0:
        print("风险回报比",M*g[1]*peilv[1]/M/g[1])
    print("只压平投入：",M*g[2])
    print("最终结果为负局的获利：",x[2]*peilv[2]-M*g[2],'预测概率为',plist[2])
    print("损失：",M*g[2],'的概率',1-plist[2])
    if g[1]!=0:
        print("风险回报比",M*g[2]*peilv[2]/M/g[2])

W投注 127.44266799999995
P投注 -5.009881398621019e-15
F投注 -4.9960036108132044e-15
投入资金总数： 127.44266799999995
最终结果为胜利的获利： 764.6560079999997 预测概率为 0.27286889
最终结果为平局的获利： -127.44266799999997 预测概率为 0.25859302
最终结果为负局的获利： -127.44266799999997 预测概率为 0.46853809
与只投注一种结果相比
只压胜投入： 127.44266799999995
最终结果为胜利的获利： 637.2133399999998 预测概率为 0.27286889
损失： 127.44266799999995 的概率 0.72713111
风险回报比 6.0
只压平投入： 0
最终结果为平局的获利： -1.8286067104966717e-14 预测概率为 0.25859302
损失： 0 的概率 0.74140698
只压平投入： 0
最终结果为负局的获利： -7.144285163462882e-15 预测概率为 0.46853809
损失： 0 的概率 0.53146191
